name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure CMake
      env:
        BUILD_TYPE: Release
        # Do not run deferred task tests on macOS. Performance is bad so the results are unpredictable.
        SPINDLE_WORKER_DEFERRED_TASK_TESTS_SKIP: ${{ runner.os == 'macOS' }}
      run: |
        cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
              -DSPINDLE_WORKER_DEFERRED_TASK_TESTS_SKIP=${SPINDLE_WORKER_DEFERRED_TASK_TESTS_SKIP} \
              -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Run unit tests
      run: ctest --test-dir ${{github.workspace}}/build -R unit-tests -V

    - name: Run benchmarks
      run: ctest --test-dir ${{github.workspace}}/build -R spindle-benchmarks -V
